export default {
  default: '📚',
  // eslint-disable-next-line @typescript-eslint/naming-convention
  chemistry:'🧪',
  biology:'🧪',
  physics:'🧪',
  anatomy:'🧪',
  history:'⌛',
  artHistory:'🧪',
  math:'π√',
  nutrition:'🧪',
  english:'🧪',
  spanish:'🇪🇸',
  french:'🇫🇷',
  chinese: '🇨🇳',
  hebrew:'🇮🇱',
  russian:'🇷🇺',
  italian:'🧪',
  latin:'🧪',
  arabic:'🧪',
  computerScience:'🧪',
  calculus:'🧪',
  organicChemistry:'🧪',
  biochemistry:'🧪',
  neuroscience:'🧪',
  business:'🧪',
  macroEconomics:'🧪',
  microEconomics:'🧪',
  economics:'🧪',
};

